apiVersion: apps/v1
kind: Deployment
metadata:
  name: devboard-fe-deployment
  namespace: devboard
  labels:
    app: devboard-fe
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devboard-fe
  template:
    metadata:
      labels:
        app: devboard-fe
    spec:
      containers:
      - name: devboard-fe
        image: sangitasahoo/devboard-fe:latest
        ports:
        - containerPort: 5173
