# Goal - To Run End to End DevSecOps CI Pipeline

name: DevSecOps

on:
    push:
        branches: [gitops]

jobs:

    code-quality:
        uses: ./.github/workflows/code-quality.yaml

    secret-scanning:
        uses: ./.github/workflows/secrete-scan.yaml

    dependency-checks:
        uses: ./.github/workflows/dependency-check.yaml
