# Goal: To Run end to end DevSecOps pipeline 

name: DevSecOps

on:
  push:
    branches: [feat/docker]

jobs:
  
    code-quality:
        uses: ./.github/workflows/code-quality.yaml

    scan_secretes:
        uses: ./.github/workflows/secrete-scan.yaml
    
    dependency-scan:
        uses: ./.github/workflows/dependency-check.yaml

    docker-check:
        uses: ./.github/workflows/docker-scan.yaml

